apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/hardy-ivy-440422-u0/backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "34.70.156.149"
        - name: DB_USER
          value: "root"
        - name: DB_PORT
          value: "3306"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "OpsMerge"
